services:
  nginx:
    image: heavymetal0/digital-spb_ml-nginx:latest
    ports:
      - "80:80"
    networks:
      - my_network

  api:
    image: heavymetal0/digital-spb_ml-api:latest
    ports:
      - "8080:8080"
    networks:
      - my_network
  
  ai:
    image: heavymetal0/digital-spb_ml-ai:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  
  tree2:
    image: heavymetal0/digital-spb_ml-tree2:latest
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
