FROM golang:1.24 AS builder

WORKDIR /app

# Копируем go.mod и go.sum из src
COPY go.mod ./
RUN go mod tidy

# Копируем весь src в рабочую директорию
COPY . .

# Сборка main.go
RUN GOOS=linux GOARCH=amd64 go build -o main main.go

# Финальный минимальный образ
FROM gcr.io/distroless/base

WORKDIR /root/

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
