FROM python:3.13-slim

WORKDIR /app

COPY ./code /app
COPY requirements.txt /app/

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*


RUN pip install -r requirements.txt


#EXPOSE 5000

# Command to run the script
CMD ["python", "-u", "app.py"]